### ISSUE TITLE
Still got "AttributeError" after copying the Python script containing the "ContrastiveModel" class to the same folder as "main.py".

### ISSUE THREAD

**Issue by DerrickGuu** [YijinHuang/pytorch-classification#11]
%%%

1. The "AttributeError" is caused by the pickle mechanism, which means you need to copy the Python script containing the "ContrastiveModel" class to the same folder as "main.py".

%%%

_Originally posted by @YijinHuang in https://github.com/YijinHuang/pytorch-classification/issues/10#issuecomment-2188984591_

I still got the same attribute error after doing so. Are there any further detailed instructions about how can I train the classification model to evaluate the weights from [Lesion-based-Contrastive-Learning](https://github.com/YijinHuang/Lesion-based-Contrastive-Learning)? Or are there any other parts I have to modify in the script? 

Thanks for the help! 

![圖片_2024-06-28_021402767](https://github.com/YijinHuang/pytorch-classification/assets/157399496/1fa5acab-d067-44b6-ba04-76ebf590920d)

**Comment by YijinHuang** [comment]
Thank you for helping me find this bug. I have uploaded a script in the [Lesion-based-Contrastive-Learning](https://github.com/YijinHuang/Lesion-based-Contrastive-Learning) repository that can be used to process your pre-trained model so it can be directly loaded in [pytorch-classification](https://github.com/YijinHuang/pytorch-classification). 

Please find the script `tools/model2weights.py` in the Lesion-based CL repository and run it with the following command:

```bash
python model2weights.py --pretrained-model [path/to/your/model] --output [path/to/new/file]
```

Then update the "checkpoint" item in `~/configs/eyepacs.yaml` with `[path/to/new/file]`. Make sure to keep `strict=False` in `load_state_dict`.

Additionally, I have updated the method for saving pre-trained models in the Lesion-based CL repository. If you use the latest code, you won't need to run this script.

**Comment by DerrickGuu** [comment]
Thanks for solving this issue! It worked fine to me, and now the results from Lesion-based CL can be directly loaded!

**Comment by DerrickGuu** [comment]
Thanks for solving this issue! It worked fine to me, and now the results from Lesion-based CL can be directly loaded!
