### ISSUE TITLE
关于您代码中优化器的一点小疑问。

### ISSUE THREAD

**Issue by zeng-su123** [YijinHuang/pytorch-classification#2]
您好！
又来向您请教问题了，最近又在您的代码上调参数，发现了一件很奇怪的现象。您默认使用的是SGD+nesterov方法，看您的代码也写了ADAM优化器，不知道为什么我把优化器换成ADAM之后，效果非常差，直接无法正常工作。 kappa指标一直为0，acc也保持不变，想来全预测为类别0了，如图所示，请问您碰到了这个情况吗？

微信图片_20220613154349
祝您安好！

**Comment by zeng-su123** [comment]
![微信图片_20220613154349](https://user-images.githubusercontent.com/66894541/173363290-fa1013db-7107-4b1a-907d-aa601873295d.jpg)
图片复制错误了，在这个位置。

**Comment by YijinHuang** [comment]
您好，如果变更了优化器的话，学习率也得相应调整。在这个配置中，默认的0.001的学习率对于Adam optimizer来说太高了，所以训练失败了。我简单试了一下0.00003的学习率，在测试集能达到大约80%的Kappa。您可以根据验证集的表现，调整一下学习率或其它超参，进一步提升这个结果。谢谢！
