### ISSUE TITLE
关于多卡训练无法复现的疑问

### ISSUE THREAD

**Issue by LPudding** [YijinHuang/pytorch-classification#4]
您好，我是北航的一名研究生，非常感谢您在eyepacs上的调参训练结果。

根据您的环境要求，我配置了相同版本的环境。单卡训练时，我发现实验结果是可以复现的。但是我在多卡训练时遇到了一些问题，根据您的设置，random_seed=1，cudnn_deterministic=true，但是实验结果无法复现。可能我错误使用了您的代码，但我没能找到具体的原因，非常抱歉打扰您，能请您帮忙分析一下吗，十分感谢！

祝您安好！

**Comment by YijinHuang** [comment]
您好，感谢您对我们工作的兴趣。

由于在多卡训练的情况下，样本会分配给多个process训练（每个process处理的样本不同），因此即使随机种子设置与单卡情况下相同，也无法得到与单卡完整一致的结果。请问您多卡的结果是多少？我使用双卡的kappa为82.9%，单卡下为83.1%。我认为在单次实验下，0.2%的差距属于正常的随机数波动。

此外，由于设置了随机种子，同个batch下，每个process会对所接收的不同样本做相同的数据增强，所以当用过多的卡训练，可能会降低数据增强的diversity，从而影响训练结果。这种问题可以通过给每个process设置不同随机种子来解决。我没做过此类实验，但我觉得影响应该也不大。

**Comment by LPudding** [comment]
您好，非常感谢您对我问题的回答。

很抱歉我没能将问题讲清楚，我的问题是在多卡情况下实验结果不能复现（两次多卡训练的第一个epoch结束时的结果并不一致），没有跑满25个epoch的原因是我跑多卡时会出现程序卡死的情况（gpu占用100%，没退出但程序停止了，估计是多进程死锁了，这个问题一直没能解决），我想请问您之前有遇到这样的问题吗？

祝您安好！

**Comment by YijinHuang** [comment]
非常感谢您指出这个问题。多卡模式下，我仅在主程序设置了随机种子，因此导致结果不可复现。我已经更新代码了，请您使用新的代码再尝试下。

关于卡死的情况，我并没有遇到过。是在固定的一个epoch卡死吗？您看下终止程序时候的报错信息，是卡死在哪一行代码呢？

**Comment by LPudding** [comment]
您好，非常感谢您的修改，更新后多卡模式可复现了，并且能够顺利跑通并且没有出现卡死的情况。

十分感谢您的帮助！

祝你安好！
